version: 2.1

# 実行するjob
jobs:
  # buildするjob
  build:
    machine:
      #image: cimg/php:8.0.11
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: env copy
          command: cp .env.example .env
      - run:
          name: docker-compose build
          command: docker-compose build
  # testするjob
  test:
    machine:
      #image: cimg/php:8.0.11
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: env copy
          command: cp .env.example .env
      - run:
          name: docker-compose up -d
          command: docker-compose up -d
      #- run: sleep 30
      - run:
          name: docker-compose run app composer install
          command: docker-compose run app composer install
      - run:
          name: docker-compose run app cp .env.example .env
          command: docker-compose run app cp .env.example .env
      - run:
          name: docker-compose run app php artisan key:generate
          command: docker-compose run app php artisan key:generate
      # - run:
      #     name: docker-compose run back rails db:create RAILS_ENV=test
      #     command: docker-compose run back rails db:create RAILS_ENV=test
      # - run:
      #     name: docker-compose run back rails db:migrate RAILS_ENV=test
      #     command: docker-compose run back rails db:migrate RAILS_ENV=test
      # - run:
      #     name: docker-compose run back bundle exec rspec spec
      #     command: docker-compose run back bundle exec rspec spec
      - run:
          name: docker-compose run app php artisan test
          command: docker-compose run app php artisan test
      - run:
          name: docker-compose down
          command: docker-compose down

# 順番を制御するworkflow
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
